### ISSUE TITLE
`.proc.proctype` to replace command line args

### ISSUE THREAD

**Issue by danielkrizian** [poetiq/poetiq#14]
From `q torq.q -usage`:

>  Currently each process has to know two things about itself - it's name and type.  These can be
> - read from a file (the default behaviour)
> - supplied on the command line
> - set previously if sourced from other files (set .proc.proctype and .proc.procname)

**Comment by mortensorensen** [comment]
Does 'startp'/'start.csv' solve this? By default all configuration should be set in a config file. Any remaining config which can't be set from a file should be defined in 'start.csv'.

**Comment by danielkrizian** [comment]
Yes that would be the solution. In the present implementation, `startp` launches set of processes. We might want to make it more flexible.
Yesterday with @tdfirth we have white-boarded two types of config files (btw q files with namespaces, resembling `config/settings/x.q): 
1. **process config** - `get(a.k.a load or pull or sync) at initialisation phase of the process; specified by admin/developer;
2. **strategy config** - `set (a.k.a push or async) at configuration phase to (re)define behavior of different, already initialised components/processes; set by user; example: use equal weight portfolio construction, later change  over life of the strategy to market cap weighted
3. **developer config** (terminal multiplexing, graphical preferences etc) - completely custom preferences and specific to each developer tastes and environment.

The advantage of q files is that lists don't impose rectangular (tabular) structure like csv and are easier to parse from, well, q, in bulk :) Environments, directory trees, namespaces - everything is a list - native citizen of q!

Will put up stuff we came up with on the wiki today.

So yeah, I definitely envisage file like:

```
\d .btfeed
.proc.proctype: `btfeed
.proc.name: `btfeed1
.proc.port: 5016
.other.param.to.replace.your.typical.cmd.line.argument: `iztru

\d .bttickerplant
.proc.proctype: `bttickerplant
.proc.name: `bttickerplant1
.proc.port: @[isavailable; 5012; getnextavailableportfromrange[]]
```

The above can be split across separate files by (`\d` namespace) if more convenient - i.e. default/example configuration file for each component, stored in the subdirectory of the process type, e.g. `src/bttickerplant/`.

q namespaces are easier to manipulate than directory trees or command line arguments.

On a related note, is it possible to spawn new process from within q using `system "q torq.q -proc.type bttickerplant -p 5017"` ?

**Comment by mortensorensen** [comment]
Can't 1) and 2) just be done with the normal config files in `config/settings`?

3) should be loaded prior to q, so I don't think q files are an option here - they need to be parsed by Bash, which is why they're currently in CSV format.

Regarding spawning processes from within q - sure it's possible. Not quite sure if they will exit when the controlling process exits (unless prefixed with `nohup`).

**Comment by danielkrizian** [comment]
> Can't 1) and 2) just be done with the normal config files in `config/settings`?

I actually want to come up with `src/processtypeX/configfile.q` for 1) and `src/strategy/configstrategy1.q` for 2). 
They will just be init defaults for first, example/demo for latter - not set in stone. Hence separating 1) from 2) and away from global god-like `config/settings` makes sense. Another reason is that 1) get set at different stage than 2) and by different method ( 1- get, 2- set). More on this later.

> 3) should be loaded prior to q, so I don't think q files are an option here

Agreed, just 1) and 2) seem to be q files.
