### ISSUE TITLE
Separate app code from TorQ code

### ISSUE THREAD

**Issue by danielkrizian** [poetiq/poetiq#16]

**Comment by mortensorensen** [comment]
I agree very much with this point. Much of the code is depending on the env variable `KDB_CODE`, so I am not sure how easy it is to separate. Ideally, I would like to see a folder structure like this

```
- bin
- config
- lib
- src
-- torq
-- tick
-- <module A>
--- test
----fixtures
--- config.csv
```

So each module has it own folder and contains its own config files, tests, etc.

**Comment by tdfirth** [comment]
I agree (if it is possible) re your proposed file structure Morten...that structure is logical and is used in many other projects so it is quick to pick up.  Speaking from very recent/current experience as someone who is new to both the project and TorQ it is difficult to separate out TorQ logic from business logic on at present.

**Comment by danielkrizian** [comment]
Perhaps breaking down env variables (esp. the currently all-embracing `$POETIQ`) from https://github.com/danielkrizian/poetiq/blob/master/bin/setenv.sh
into more granular `$TORQHOME`, `$POETIQHOME`, `$KDBCONFIG`, `$KDBAPPCONFIG`
inspired by 
http://www.aquaq.co.uk/q/torq-packaging/
https://github.com/AquaQAnalytics/TorQ-Finance-Starter-Pack/blob/master/setenv.sh

The idea is to group TorQ code under `$TORQHOME` and our business code under `$POETIQHOME`
Even better(shorter) names: `$TORQ` and `$POETIQ`.

Tying to your proposed tree, perhaps 

```
export PROJECT=./
export TORQ=${PROJECT}/src/torq
export POETIQ=${PROJECT}/src
export KDBCONFIG=${PROJECT}/config
export KDBAPPCONFIG=${PROJECT}/appconfig
```

Something like that

**Comment by danielkrizian** [comment]
We also need to make sure the `<module foo>` folders are truly replaceable/modular to allow plug&play functionality: e.g. to replace mean-variance portfolio optimiser with stratified sampling portfolio constructor for example by just pointing the launch script to different directory/source file
