### ISSUE TITLE
Patchy hdb loading from other processes

### ISSUE THREAD

**Issue by danielkrizian** [poetiq/poetiq#27]
Find unified point of access to historical database and adhoc datasets outside the process.

Remove the need for ad-hoc loading of hdb dependencies such as `\l hdb/equitysim` here:
https://github.com/poetiq/poetiq/blob/modular-folders/src/fillsim/f.q#L14

The above depends on correct directory so we are currently hacking with `cd` here:
https://github.com/poetiq/poetiq/blob/modular-folders/config/settings/default.q#L1

The issue is that the process (fillsim in this case, but all subscribers as well) ends up in this state:

```
q)system "cd"
"F:\\gdrive\\q\\poetiq\\hdb\\equitysim"

```

**Comment by mortensorensen** [comment]
The HDB should be a process in itself and not loaded through other processes by `\l`. If a process needs data from the HDB it should get its handle from Discovery and query it through its handle or a gateway.
