### ISSUE TITLE
Usage of Projects

### ISSUE THREAD

**Issue by mortensorensen** [poetiq/poetiq#29]
I just noticed the Projects page and found it quite useful. I was thinking if we should start logging everything we do in Issues or Projects and refer to that in our commit messages.

I could have a project called Launch Control (id #123). I would prefix each commit message related to that project with e.g. "#123 update something".

Not sure if you're using JIRA at your company? But it's the same concept. It's quite useful to see what the other guys are working on. And if you're in doubt why I just pushed a particular commit, you can refer to the Issue page for more details.

**Comment by danielkrizian** [comment]
Absolutely! Currently there is only one single project titled `poetiq`. Makes sense to rather have multiple mini-projects like "Launch Control" or "Project Tree Redesign" and assign each `issue` to one or multiple  of the projects (note that even this issue `Usage of Projects #29` shows Projects assignment on the right tray.  

> I would prefix each commit message related to that project with e.g. "#123 update something".

No need to do that manually and clog the text of commit with project prefix. You can just refer to #issueid and Github links each issue to project automatically, assuming you assigned the issue to project using that new Github kanban tool.
